### PR TITLE
PhoneGap CLI 6.0.0 Blog Post

### PR DESCRIPTION
**Pull request by mwbrooks**
@hollyschinsky can you give this a proof-read for content before I merge it into `master`?

@GarthDB can you give this a look over for any errors - it's my first attempt at sending a PR for a blog post.

### CODE REVIEW

**Comment by mwbrooks** [comment]
Hmmm... looks like my image was uploaded to `master` instead of my branch. You can't upload images to a specific branch it seems. I'll have to do it locally...

**Comment by GarthDB** [comment]
Yeah. I noticed that today. It seems like a weird limitation.

**Comment by GarthDB** [comment]
It builds and looks good.

**Comment by mwbrooks** [comment]
@GarthDB okay, I've uploaded the image. Can you verify that the relative path that I'm using will work in production? Seems like it.

**Comment by GarthDB** [comment]
Yup - it works.

**Comment by mwbrooks** [comment]
Sweet, thanks @GarthDB!

@hollyschinsky when you have a chance, mind giving this a proof-read for content?

**Pull request merged**
